# This file is only a reference/example.
# start.sh creates /etc/asound.conf dynamically from the INFERNO_* variables.
pcm.inferno_raw {
    type inferno
    NAME "Spotify-Dante"
    SAMPLE_RATE "48000"
    TX_CHANNELS 1
    RX_CHANNELS 0
    BIND_IP "169.254.10.19"
    DEVICE_ID "0000020000001081"
    PROCESS_ID 90
    ALT_PORT 15800
    CLOCK_PATH "/shared/usrvclock"
    TX_LATENCY_NS 10000000
    RX_LATENCY_NS 10000000
}
